select  id, 
        symbol, 
        name, 
        image,
        CAST(last_updated AS timestamptz)   as last_updated,
        CAST(extracted_at AS timestamptz)   as extracted_at,
        current_price, 
        high_24h, 
        low_24h, 
        price_change_24h,
        price_change_percentage_24h,
        market_cap, 
        market_cap_rank, 
        market_cap_change_24h, 
        market_cap_change_percentage_24h, 
        fully_diluted_valuation, 
        total_volume,
        circulating_supply, 
        total_supply,
        cast(cast(max_supply as text) as numeric) as max_supply,
        ath, 
        ath_change_percentage, 
        CAST(ath_date AS timestamptz)       as ath_date, 
        atl, 
        atl_change_percentage, 
        CAST(atl_date AS timestamptz)       as atl_date,
        _id as id_mongo
from {{ source('airbyte_crypto', 'top5_NovaVersao') }}